### ISSUE TITLE
Create a class to manage animation refresh rate

### ISSUE THREAD

**Issue by elijah-t** [Project-Rekt/engine#14]
# Animation refresh rate
## Animations have a refresh rate that allow the sprite to have a buffer into it's next state, based on frames per second. This class will allow the customization of number of refreshes based on frames per second.

**Comment by Squishy123** [comment]
Do we want to have a class to manage this, or should we combine it in the sprite schema?

**Comment by elijah-t** [comment]
Now that you mention it, it would probably be good combined with the sprite schema; we could have refresh rate be one of its properties.

**Comment by Squishy123** [comment]
let's move this issue to the other one then
