### ISSUE TITLE
Add a priority to keydown event listening

### ISSUE THREAD

**Issue by Squishy123** [Project-Rekt/engine#22]
If you press multiple keys with a small delay in between presses, there should be a priority of key pressed.

**Comment by OneHandKlap** [comment]
Do you mean that keys should be executed according to a priority schema instead of order of pressing?

**Comment by Squishy123** [comment]
actually i think this is non-issue since the keydown will catch all button presses and then the flag is set to true on this.input.keys()

closes #22
